### PR TITLE
[feat] & [Refactor]: signup/login/Footer files changed

### PR DESCRIPTION
**Pull request by Logan1x**
This Pr has changed in the following screens
- Signup implemented
- login function args changed to object
- test credentials button added on the login
- footer refactor
- Link tag added instead of anchor tag in Nav 
- Added OG Meta Tags
- Test login button added
- Category Feat implemented

### CODE REVIEW

**Review by thegeorgenikhil — COMMENTED** [review]
Suggestion: use userData instead of uData

**Review by thegeorgenikhil — APPROVED** [review]
Good UI.
Just a suggestion to improve the variable naming of the user data.
Good to merge.

**Review by rohit8686 — APPROVED** [review]
Clean code, looks good to merge

**Review by varnita619 — APPROVED** [review]
Code is clean
Consistency in all units
Ready to  merge

**Comment by Logan1x** [comment]
Thanks, Everyone. merging Now

**Pull request merged**
